apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world
spec:
  hosts:
    - "*"
  gateways:
    - gateway-hello
  http:
    - route:
        - destination:
            host: hello-world.default.svc.cluster.local
            port:
              number: 80